# Generated by Django 5.1.2 on 2025-03-30 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('purpose', models.CharField(blank=True, choices=[('donate', 'Donate'), ('assistance', 'Assistance')], max_length=50, null=True)),
                ('contact_method', models.CharField(blank=True, choices=[('email', 'Email'), ('phone', 'Phone')], max_length=50, null=True)),
                ('donation_type', models.CharField(blank=True, max_length=100, null=True)),
                ('needs_description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Join',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('why', models.TextField()),
                ('message', models.TextField()),
                ('availability', models.CharField(max_length=100)),
            ],
        ),
    ]
